# Generated by Django 3.2.15 on 2023-06-05 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
